name: microscale-llm
channels: [conda-forge]
dependencies:
  - python=3.10
  - pytorch>=2.3
  - pip
  - psutil
  - scikit-learn
  - pip:
      - transformers==4.45.2
      - datasets==3.0.1
      - evaluate==0.4.3
      - accelerate==1.0.1
      - torchmetrics==1.4.2
      - onnx==1.16.2
      - onnxruntime==1.19.2
      - onnxruntime-tools==1.7.0
      - tabulate==0.9.0
